/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectohotel;

//Agregar los import necesarios para las clases de manejo de archivos
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

import javax.swing.JFileChooser;
//Importar las clases neceasrios para la GUI
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import Clases.ReservaHabitacion;

/**
 *
 * @author equipo
 */
public class FormularioReservaciones extends javax.swing.JFrame {
    private static FormularioReservaciones instancia = null;
    private static FormularioHistorial formularioHistorial;
    private String ubicacionArchivo;
    private int contadorRegistros = 1;
    private final boolean[] habitacionesOcupadas = new boolean[6];

    /**
     * Creates new form Reservaciones
     */
    public FormularioReservaciones() {
        initComponents();
        formularioHistorial = FormularioHistorial.obtenerInstancia();
    }

    public static FormularioReservaciones obtenerInstancia() {
        if (instancia == null) {
            instancia = new FormularioReservaciones();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbInstruccion1 = new javax.swing.JLabel();
        lbClave = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbNumeroHabitacion = new javax.swing.JLabel();
        lbTiempo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        comboNumeroHabitacion = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbHabitacion = new javax.swing.JLabel();
        lbEstancia = new javax.swing.JLabel();
        comboTiempo = new javax.swing.JComboBox<>();
        lbClaveNumero = new javax.swing.JLabel();
        lbAviso = new javax.swing.JLabel();
        txtAviso2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbInstruccion1.setText("1. Ingresa la información");

        lbClave.setText("Clave del cliente");

        lbNombre.setText("Nombre del cliente");

        lbFecha.setText("Fecha de reservacion");

        lbNumeroHabitacion.setText("Número de habitación");

        lbTiempo.setText("Tiempo de reservación");

        comboNumeroHabitacion
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSeleccionar.setText("Seleccionar ubicacion");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lbHabitacion.setText("Habitación:");

        lbEstancia.setText("Noche(s):");

        comboTiempo
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        lbClaveNumero.setText("1");

        lbAviso.setText("Aviso");

        txtAviso2.setText("Guardado en: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbInstruccion1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 375,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                        .createSequentialGroup()
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lbClave)
                                                                .addComponent(lbNombre)
                                                                .addComponent(lbFecha)
                                                                .addComponent(lbNumeroHabitacion)
                                                                .addComponent(lbTiempo))
                                                        .addGap(36, 36, 36)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(lbClaveNumero,
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(txtFecha,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(lbHabitacion)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(
                                                                                                comboNumeroHabitacion,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(btnSeleccionar))
                                                                        .addComponent(txtNombre,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                350,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(lbEstancia)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(comboTiempo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(btnGuardar)))
                                                                .addComponent(btnSalir)))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                layout.createSequentialGroup()
                                                                        .addComponent(lbAviso)
                                                                        .addGap(485, 485, 485))
                                                        .addComponent(txtAviso2))))
                                .addContainerGap(40, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbInstruccion1))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbClave)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbClaveNumero)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbNombre))
                                                .addGap(14, 14, 14)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbFecha))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(comboNumeroHabitacion,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbHabitacion)
                                                        .addComponent(lbNumeroHabitacion)
                                                        .addComponent(btnSeleccionar))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(lbEstancia)
                                                                        .addComponent(comboTiempo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lbTiempo)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                layout.createSequentialGroup()
                                                                        .addGap(8, 8, 8)
                                                                        .addComponent(btnGuardar)))))
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAviso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAviso2)
                                .addGap(9, 9, 9)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 1. Seleccionar carpeta
    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSeleccionarActionPerformed
        JFileChooser seleccionArchivo = new JFileChooser();
        seleccionArchivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = seleccionArchivo.showDialog(this, "Seleccionar");

        if (result == JFileChooser.APPROVE_OPTION) {
            ubicacionArchivo = seleccionArchivo.getSelectedFile().getAbsolutePath();
        }
    }// GEN-LAST:event_btnSeleccionarActionPerformed

    // 2. Guardar datos en archivo txt
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        lbClaveNumero.setText(Integer.toString(contadorRegistros));
        String claveClienteStr = Integer.toString(contadorRegistros);
        String nombreCliente = txtNombre.getText();
        String fechaReservacion = txtFecha.getText();
        String numeroHabitacionStr = (String) comboNumeroHabitacion.getSelectedItem();
        String tiempoStr = (String) comboTiempo.getSelectedItem();
        // Validar que los campos no estén vacíos
        if (nombreCliente.trim().isEmpty() || fechaReservacion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete los campos de Nombre y Fecha.");
            return; // Detener la ejecución del método si hay campos vacíos
        }
        try {
            int claveCliente = Integer.parseInt(claveClienteStr);
            int numeroHabitacion = Integer.parseInt(numeroHabitacionStr);
            int tiempo = Integer.parseInt(tiempoStr);

            ReservaHabitacion habitacion = new ReservaHabitacion(claveCliente, nombreCliente, fechaReservacion,
                    numeroHabitacion, tiempo);

            // Nueva línea: Llamar al método para crear el hilo de reserva
            crearHiloReserva(habitacion);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese números válidos en los campos correspondientes.");
        }
    }

    // 2.1 Hilo para gestionar el tiempo de reserva de las habitaciones
    private void crearHiloReserva(ReservaHabitacion habitacion) {
        Thread hiloReserva = new Thread(() -> {
            try {// Obtener datos de la reservación
                int numeroHabitacion = habitacion.getNumeroHabitacion();
                int noches = habitacion.getNocheEstancia();
                int tiempoEstancia = noches * 24; // 1 noche = 24 segundos
                // Reservar habitacion
                if (habitacionesOcupadas[numeroHabitacion]) {
                    mostrarMensaje("La habitación " + numeroHabitacion + " está ocupada. Deberá esperar.");
                } else {
                    habitacionesOcupadas[numeroHabitacion] = true;
                    crearArchivo(habitacion);
                    // Simular tiempo de estancia. Mostrar cómo transcurre el tiempo en lbAviso
                    for (int tiempoTranscurrido = 0; tiempoTranscurrido <= tiempoEstancia; tiempoTranscurrido++) {
                        final String mensaje = "Tiempo restante para la habitación " + numeroHabitacion + ": "
                                + (tiempoEstancia - tiempoTranscurrido) + " segundos.";
                        // Actualizar lbAviso con el tiempo restante
                        SwingUtilities.invokeLater(() -> lbAviso.setText(mensaje));
                        Thread.sleep(1000); // Dormir durante 1 segundo antes de la próxima actualización
                    }
                    // Liberar habitación
                    habitacionesOcupadas[numeroHabitacion] = false;
                    // Mostrar el mensaje de liberación con el número de la habitación
                    mostrarMensaje("Habitación " + numeroHabitacion + " liberada. Tiempo concluido.");
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        });
        hiloReserva.start();
    }

    // 2.2
    private void mostrarMensaje(String mensaje) {
        SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, mensaje));
    }

    // 2.3
    private void crearArchivo(ReservaHabitacion habitacion) {
        String nombreArchivo = "reservas.txt"; // Nombre predeterminado del archivo
        if (ubicacionArchivo == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una ubicación.");
            return;
        }

        try {
            String direccionCompleta = ubicacionArchivo + "/" + nombreArchivo;
            FileWriter fileWriter = new FileWriter(direccionCompleta, true);
            PrintWriter printWriter = new PrintWriter(fileWriter);

            // Escribir los datos en el archivo
            printWriter.println("Clave del cliente: " + contadorRegistros++);
            printWriter.println("Nombre del cliente: " + habitacion.getNombreCliente());
            printWriter.println("Fecha de reservación: " + habitacion.getFechaReservacion());
            printWriter.println("Número de habitación: " + habitacion.getNumeroHabitacion());
            printWriter.println("Noches de estancia: " + habitacion.getNocheEstancia());
            printWriter.println(
                    "------------------------------------------------------------------------------------\n");
            printWriter.close(); // Cerrar el archivo
            JOptionPane.showMessageDialog(this, "La reserva se ha guardado en " + direccionCompleta);
            lbClaveNumero.setText(Integer.toString(contadorRegistros));
            txtAviso2.setText("Guardado en: " + direccionCompleta);
            // Recuperar los datos en la tabla de Historial
            formularioHistorial.agregarRegistroHistorial(habitacion);
            limpiarCampos();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al escribir en el archivo.");
        }
    }

    // 2.4
    private void limpiarCampos() {
        txtNombre.setText("");
        txtFecha.setText("");
    }

    // 3. Salir
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioReservaciones.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioReservaciones.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioReservaciones.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioReservaciones.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioReservaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> comboNumeroHabitacion;
    private javax.swing.JComboBox<String> comboTiempo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAviso;
    private javax.swing.JLabel lbClave;
    private javax.swing.JLabel lbClaveNumero;
    private javax.swing.JLabel lbEstancia;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHabitacion;
    private javax.swing.JLabel lbInstruccion1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumeroHabitacion;
    private javax.swing.JLabel lbTiempo;
    private javax.swing.JLabel txtAviso2;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
